# Algorithms Exercise 2

## Imports

In [88]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

## Peak finding

Write a function `find_peaks` that finds and returns the indices of the local maxima in a sequence. Your function should:

* Properly handle local maxima at the endpoints of the input array.
* Return a Numpy array of integer indices.
* Handle any Python iterable as input.

In [114]:
def find_peaks(a):
    """Find the indices of the local maxima in a sequence."""
    maxima = []
    length = len(a)
    if length >= 2:
        if a[0] > a[1]:
            p = 0
            maxima.append(p)
            
    if length > 3:
        for i in a:
            if a[i] > a[i-1] and a[i] > a[i+1]:
                q = np.nonzero(a[i])
                maxima.append(q)
    
    if a[length-1] > a[length-2]:
        r = a[length-1]
        maxima.append(r)        
    return maxima


find_peaks([2,0,1,0,2,0,1])

        
    

[0,
 (array([0]),),
 (array([0]),),
 (array([0]),),
 (array([0]),),
 (array([0]),),
 1]

In [109]:
a = [1,3,6,4,5,1]
find_peaks(a)

IndexError: list index out of range

In [87]:
p1 = find_peaks([2,0,1,0,2,0,1])
assert np.allclose(p1, np.array([0,2,4,6]))
p2 = find_peaks(np.array([0,1,2,3]))
assert np.allclose(p2, np.array([3]))
p3 = find_peaks([3,2,1,0])
assert np.allclose(p3, np.array([0]))

ValueError: operands could not be broadcast together with shapes (7,) (4,) 

Here is a string with the first 10000 digits of $\pi$ (after the decimal). Write code to perform the following:

* Convert that string to a Numpy array of integers.
* Find the indices of the local maxima in the digits of $\pi$.
* Use `np.diff` to find the distances between consequtive local maxima.
* Visualize that distribution using an appropriately customized histogram.

In [1]:
from sympy import pi, N
pi_digits_str = str(N(pi, 10001))[2:]

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert True # use this for grading the pi digits histogram