In [61]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [62]:
import antipackage
from github.ellisonbg.misc import vizarray as va

In [63]:
import numpy as np

In [104]:
data = [0,2,4,6]
a = np.array(data)

In [105]:
type(a)

numpy.ndarray

In [106]:
a

array([0, 2, 4, 6])

In [107]:
va.vizarray(a)

In [108]:
a.shape

(4,)

In [109]:
a.ndim

1

In [110]:
a.size

4

In [111]:
a.nbytes

32

In [112]:
a.dtype

dtype('int64')

In [113]:
data = [[0.0,2.0,4.0,6.0], [1.0,3.0,5.0,7.0]]
b = np.array(data)

In [114]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.]])

In [115]:
va.vazarray(b)

AttributeError: 'module' object has no attribute 'vazarray'

In [116]:
b.shape, b.ndim, b.size, b.nbytes 

((2, 4), 2, 8, 64)

In [117]:
c = np.arange(0.0,10.0,1.0)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [118]:
e = np.linspace(0.0, 5.0, 11)
e

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [119]:
np.empty((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [120]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [121]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [122]:
np.empty_like((3,3))

array([0, 0])

In [123]:
a = np.array([0,1,2,3])

In [124]:
a, a.dtype

(array([0, 1, 2, 3]), dtype('int64'))

In [125]:
b = np.zeros((2,2), dtype = np.complex64)
b

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]], dtype=complex64)

In [144]:
c = np.arange(0, 10, 2, dtype=np.float)
c

array([ 0.,  2.,  4.,  6.,  8.])

In [145]:
d = c.astype(dtype=np.int)

In [146]:
d

array([0, 2, 4, 6, 8])

In [162]:
np.float

float

In [163]:
a = np.empty((3,3))
a.fill(0.1)
a

array([[ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1]])

In [164]:
b = np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [165]:
a + b

array([[ 1.1,  1.1,  1.1],
       [ 1.1,  1.1,  1.1],
       [ 1.1,  1.1,  1.1]])

In [151]:
b/a

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.]])

In [152]:
a/b

array([[ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1]])

In [153]:
a**2

array([[ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01]])

In [154]:
np.pi*b

array([[ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265]])

In [170]:
a = np.random.rand(10,10)

In [171]:
va.enable()

In [172]:
a

array([[ 0.04975301,  0.28794271,  0.18187783,  0.43004931,  0.39537224,
         0.12343834,  0.84387647,  0.32657504,  0.05744398,  0.37953236],
       [ 0.72928162,  0.22731261,  0.60589415,  0.57485312,  0.17546155,
         0.05064034,  0.17588122,  0.69361514,  0.0871208 ,  0.42679502],
       [ 0.9077253 ,  0.93721854,  0.1456079 ,  0.72741297,  0.06413768,
         0.18820537,  0.47770691,  0.17359486,  0.44418359,  0.98459391],
       [ 0.86642271,  0.99015674,  0.78882246,  0.39027749,  0.64139049,
         0.02186293,  0.15398292,  0.95421168,  0.36673762,  0.66447167],
       [ 0.60602338,  0.43637405,  0.35945312,  0.23650816,  0.75955012,
         0.67313907,  0.82621466,  0.293359  ,  0.69352977,  0.62530847],
       [ 0.13705881,  0.16763394,  0.28288998,  0.75498399,  0.90298988,
         0.18331038,  0.58621062,  0.63943287,  0.66850194,  0.92020274],
       [ 0.64550369,  0.44955856,  0.76060619,  0.81470012,  0.18240608,
         0.92118382,  0.98769002,  0.53597152,  0.12764747,  0.79844773],
       [ 0.2378347 ,  0.63080125,  0.20290636,  0.61391382,  0.58378483,
         0.10076457,  0.92921049,  0.87897254,  0.92248554,  0.44791581],
       [ 0.60895721,  0.29020185,  0.76185342,  0.23928088,  0.61598167,
         0.7149536 ,  0.10215677,  0.20441677,  0.15379646,  0.44080362],
       [ 0.99901342,  0.88826912,  0.95150983,  0.81503405,  0.58415553,
         0.06923142,  0.38865989,  0.2522284 ,  0.22497516,  0.7995263 ]])

In [173]:
a[0,0]

0.049753008761178497

In [174]:
a[-1,-1] == a[9,9]

True

In [175]:
a[:,0]

array([ 0.04975301,  0.72928162,  0.9077253 ,  0.86642271,  0.60602338,
        0.13705881,  0.64550369,  0.2378347 ,  0.60895721,  0.99901342])

In [176]:
a[-1,:]

array([ 0.99901342,  0.88826912,  0.95150983,  0.81503405,  0.58415553,
        0.06923142,  0.38865989,  0.2522284 ,  0.22497516,  0.7995263 ])

In [177]:
a[0:2,0:2]

array([[ 0.04975301,  0.28794271],
       [ 0.72928162,  0.22731261]])

In [178]:
a[0:5, 0:5] = 1.0

In [179]:
a

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.12343834,  0.84387647,  0.32657504,  0.05744398,  0.37953236],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.05064034,  0.17588122,  0.69361514,  0.0871208 ,  0.42679502],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.18820537,  0.47770691,  0.17359486,  0.44418359,  0.98459391],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.02186293,  0.15398292,  0.95421168,  0.36673762,  0.66447167],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.67313907,  0.82621466,  0.293359  ,  0.69352977,  0.62530847],
       [ 0.13705881,  0.16763394,  0.28288998,  0.75498399,  0.90298988,
         0.18331038,  0.58621062,  0.63943287,  0.66850194,  0.92020274],
       [ 0.64550369,  0.44955856,  0.76060619,  0.81470012,  0.18240608,
         0.92118382,  0.98769002,  0.53597152,  0.12764747,  0.79844773],
       [ 0.2378347 ,  0.63080125,  0.20290636,  0.61391382,  0.58378483,
         0.10076457,  0.92921049,  0.87897254,  0.92248554,  0.44791581],
       [ 0.60895721,  0.29020185,  0.76185342,  0.23928088,  0.61598167,
         0.7149536 ,  0.10215677,  0.20441677,  0.15379646,  0.44080362],
       [ 0.99901342,  0.88826912,  0.95150983,  0.81503405,  0.58415553,
         0.06923142,  0.38865989,  0.2522284 ,  0.22497516,  0.7995263 ]])

In [180]:
va.disable()

In [181]:
ages = np.array([23,56,67,89,23,56,27,12,8,72])
genders = np.array(['m','m','f','f','m','f','m','m','m','f'])

In [182]:
ages >30

array([False,  True,  True,  True, False,  True, False, False, False,  True], dtype=bool)

In [183]:
genders == 'm'

array([ True,  True, False, False,  True, False,  True,  True,  True, False], dtype=bool)

In [186]:
(ages > 10) & (ages < 50)

array([ True, False, False, False,  True, False,  True,  True, False, False], dtype=bool)

In [187]:
mask = (genders == 'f')
ages[mask]


array([67, 89, 56, 72])

In [188]:
ages[ages>30]

array([56, 67, 89, 56, 72])